{{/*
Manager policy rules for namespaced APIs (excludes cluster-scoped openclawclusterdefaults).
Each line is unindented; parent uses nindent 2 under rules:.
*/}}
{{- define "openclaw-operator.managerRoleRulesWithoutClusterDefaults" -}}
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["openclaw.rocks"]
  resources: ["openclawinstances"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["openclaw.rocks"]
  resources: ["openclawinstances/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["openclaw.rocks"]
  resources: ["openclawinstances/finalizers"]
  verbs: ["update"]
- apiGroups: ["openclaw.rocks"]
  resources: ["openclawselfconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["openclaw.rocks"]
  resources: ["openclawselfconfigs/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["openclaw.rocks"]
  resources: ["openclawselfconfigs/finalizers"]
  verbs: ["update"]
{{- end }}

{{/*
Read-only cluster-scoped rule for OpenClawClusterDefaults singleton.
*/}}
{{- define "openclaw-operator.clusterDefaultsReaderRules" -}}
- apiGroups: ["openclaw.rocks"]
  resources: ["openclawclusterdefaults"]
  verbs: ["get", "list", "watch"]
{{- end }}
